# Generated by Django 2.1.7 on 2019-02-20 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190220_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 22, 47, 16, 646897), verbose_name='date published'),
        ),
    ]
